version: '3'

services:
  chatgpt-demo:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - pgvector
  pgvector:
    image: ankane/pgvector
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  db:
