version: '3'

services:
  law:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - pgvector
    labels:
      - "traefik.http.routers.law.rule=Host(`law.shanyue.tech`)"
      - traefik.http.routers.law.tls=true
      - traefik.http.routers.law.tls.certresolver=le

networks:
  default:
    external:
      name: traefik_default
